name: Build and Push Docker Image

on:
  push:
    branches: ["main"]  # 触发条件：当代码推送到 main 分支时

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建并推送镜像
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qinsong-ms:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qinsong-ms:${{ github.sha }}

      # （可选）清除构建缓存
      - name: Cleanup
        run: docker builder prune --force
